const express = require("express");
const router = express.Router();
const CartController = require("../controllers/Cart");
const verifyToken = require("../middleware/auth");
router.post("/addcart",verifyToken.verifyToken,CartController.AddCart);
router.put("/updatecart/:cartID",verifyToken.verifyToken,CartController.UpdateCart);
router.delete("/deletecart/:cartID",verifyToken.verifyToken,CartController.DeleteCart);
router.get("/findcartbyproductname",verifyToken.verifyToken,CartController.FindCartByName);
router.get("/getallcart",verifyToken.verifyToken,CartController.GetAllCart);
module.exports = router;