const express = require("express");
const router = express.Router();
const auth = require("./Auth");
const user = require("./User");
const product = require("./Product");
const category = require("./Category");
router.use("/auth", auth);
router.use("/user", user);
router.use("/product", product);
router.use("/category", category);
module.exports = router;
