const express = require("express");
const router = express.Router();
const ProductController = require("../controllers/Product");
const verifyToken = require("../middleware/auth");
router.post("/addproduct",verifyToken.verifyToken,ProductController.AddProduct);
router.put("/updateproduct/:productID",verifyToken.verifyToken,ProductController.UpdateProduct);
router.delete("/deleteproduct/:productID",verifyToken.verifyToken,ProductController.DeleteProduct);
router.get("/findproductbyname",verifyToken.verifyToken,ProductController.FindProductByName);
router.get("/findproductbyid",verifyToken.verifyToken,ProductController.FindProductByID);
router.get("/findproductbycategoryid",verifyToken.verifyToken,ProductController.FindProductByCategoryID);
router.get("/findproductbybrandid",verifyToken.verifyToken,ProductController.FindProductByBrandID);
router.get("/getallproduct",verifyToken.verifyToken,ProductController.GetAllProduct);
module.exports = router;